language: cpp
sudo: required
dist: xenial
before_script:
  - ls
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -y
  - sudo apt-get install g++-7 libdlib-dev -y
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90
  - gcc --version
  - g++ --version
  - cmake --version
  - sudo apt-get install libdlib-dev -y
  - git clone https://github.com/davisking/dlib.git
  - cd dlib/dlib
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - sudo make install
  - cd ../../..
script:
  - cmake .
  - cmake --build .
  - cmake --build . --target package
deploy:
  - provider: script
    skip_cleanup: true
    script:
      - curl -T kkmeans-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -ukafeg:$BINTRAY_API_KEY "https://api.bintray.com/content/kafeg/otus/homeworks/$TRAVIS_BUILD_NUMBER/kkmeans-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"
